version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
      - ~/.ssh:/home/vscode/.ssh
    command: /bin/sh -c "while sleep 1000; do :; done"